# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DotNetCoreInstaller@0
  inputs:
    version: '3.1.101'

- script: dotnet restore
  displayName: 'Restore application'

- script: dotnet build -c Release
  displayName: 'Build application'

- script: dotnet test -c Release --no-build
  displayName: 'Testing application'
